const {SlashCommandBuilder,PermissionFlagsBits:P,ChannelType,EmbedBuilder}=require("discord.js");
const commands=[],staff=["Owner","Co-owner","Manager","Administrator","Moderator","Helper"];
const S=(n,d)=>o=>o.setName(n).setDescription(d).setRequired(true);
const U=(n="user")=>o=>o.setName(n).setDescription("Member.").setRequired(true);
const C=(n,d="Channel.")=>o=>o.setName(n).setDescription(d).setRequired(true);
const I=(n,d,min,max,req=true)=>o=>{o.setName(n).setDescription(d).setRequired(req);if(min!==undefined)o.setMinValue(min);if(max!==undefined)o.setMaxValue(max)};
const cmd=(n,d,p)=>{const x=new SlashCommandBuilder().setName(n).setDescription(d);if(p)x.setDefaultMemberPermissions(p);return x};
const sub=(g,n,d,a=[])=>{g.addSubcommand(x=>{x.setName(n).setDescription(d);a.forEach(f=>f(x))});return g};
const key=(g,u)=>g.id+":"+u;
const out=(i,t)=>i.replied||i.deferred?i.followUp({content:t,ephemeral:true}):i.reply({content:t,ephemeral:true});
const opt=(i,n)=>i.options.getString(n), usr=(i,n)=>i.options.getUser(n), ch=(i,n)=>i.options.getChannel(n);

function add(...xs){commands.push(...xs)}
console.log("[The Hub] extra.js loaded with "+commands.length+" extra slash command groups.");
add(cmd("warn","Warn a member.",P.ModerateMembers).addUserOption(U()).addStringOption(S("reason","Reason.")));
add(cmd("warnings","View warnings.",P.ModerateMembers).addUserOption(U()));
add(cmd("clearwarnings","Clear warnings.",P.ModerateMembers).addUserOption(U()));
add(cmd("softban","Softban a member.",P.BanMembers).addUserOption(U()).addStringOption(S("reason","Reason.")));
add(cmd("lockdown","Lock text channels.",P.ManageChannels),cmd("unlockdown","Unlock text channels.",P.ManageChannels));
add(cmd("move","Move a member.",P.MoveMembers).addUserOption(U()).addChannelOption(C("channel","Voice channel.")));

let g=cmd("ticket","Ticket system.",P.ManageChannels);
sub(g,"open","Open a ticket.");sub(g,"panel","Post a ticket panel.",[C("channel")]);sub(g,"settings","Set ticket category.",[C("category","Category.")]);add(g);
add(cmd("ticket-panel","Post a ticket panel.",P.ManageChannels).addChannelOption(C("channel")));
add(cmd("ticket-settings","Set ticket category.",P.ManageChannels).addChannelOption(C("category","Category.")));
for(const [n,d] of [["close","Close a ticket."],["claim","Claim a ticket."],["unclaim","Unclaim a ticket."],["transcript","Create a transcript."]])add(cmd(n,d,P.ManageChannels));
add(cmd("add","Add a member to a ticket.",P.ManageChannels).addUserOption(U()),cmd("remove","Remove a member from a ticket.",P.ManageChannels).addUserOption(U()),cmd("rename","Rename a ticket.",P.ManageChannels).addStringOption(S("name","New name.")));

g=cmd("automod","Automod controls.",P.ManageGuild);for(const n of ["enable","disable","status"])sub(g,n,n+" automod.");sub(g,"config","Set blocked words.",[S("words","Comma-separated words.")]);add(g);
for(const [n,d] of [["automod-enable","Enable automod."],["automod-disable","Disable automod."],["automod-status","Show automod status."]])add(cmd(n,d,P.ManageGuild));
add(cmd("automod-config","Set blocked words.",P.ManageGuild).addStringOption(S("words","Comma-separated words.")));

for(const n of ["welcome","goodbye"]){g=cmd(n,n+" system.",P.ManageGuild);sub(g,"config","Set channel.",[C("channel")]);sub(g,"test","Test message.");add(g)}
add(cmd("welcome-config","Configure welcome channel.",P.ManageGuild).addChannelOption(C("channel")),cmd("welcome-test","Test welcome.",P.ManageGuild),cmd("goodbye-config","Configure goodbye channel.",P.ManageGuild).addChannelOption(C("channel")),cmd("goodbye-test","Test goodbye.",P.ManageGuild));

g=cmd("birthday","Birthday system.");sub(g,"set","Set birthday.",[S("date","MM-DD.")]);sub(g,"remove","Remove birthday.");sub(g,"view","View birthday.",[o=>o.addUserOption(x=>x.setName("user").setDescription("User."))]);for(const n of ["list","upcoming","today"])sub(g,n,n+" birthdays.");sub(g,"config","Set birthday channel.",[C("channel")]);sub(g,"test","Test birthday.");add(g);

g=cmd("level","Leveling system.");sub(g,"view","View level.",[o=>o.addUserOption(x=>x.setName("user").setDescription("User."))]);sub(g,"rank","View rank.",[o=>o.addUserOption(x=>x.setName("user").setDescription("User."))]);sub(g,"leaderboard","Leaderboard.");sub(g,"config","Configure leveling.",[S("enabled","true or false.")]);sub(g,"rewards","Set level reward.",[I("level","Level.",1,10000),S("role_id","Role ID.")]);add(g);
add(cmd("levels","Show leveling status."),cmd("level-config","Configure leveling.",P.ManageGuild).addStringOption(S("enabled","true or false.")),cmd("level-rewards","Set level reward.",P.ManageRoles).addIntegerOption(I("level","Level.",1,10000)).addStringOption(S("role_id","Role ID.")));

g=cmd("giveaway","Giveaway system.");sub(g,"start","Start giveaway.",[I("minutes","Duration.",1,10080),S("prize","Prize."),I("winners","Winners.",1,20,false)]);for(const n of ["end","reroll","cancel","enter"])sub(g,n,n+" giveaway.",[S("id","Giveaway ID.")]);sub(g,"list","List giveaways.");add(g);

add(cmd("suggest","Submit a suggestion.").addStringOption(S("text","Suggestion.")),cmd("suggestions","List suggestions."),cmd("suggestion-approve","Approve suggestion.",P.ManageMessages).addStringOption(S("id","ID.")),cmd("suggestion-deny","Deny suggestion.",P.ManageMessages).addStringOption(S("id","ID.")),cmd("suggestion-review","Review suggestion.",P.ManageMessages).addStringOption(S("id","ID.")));
g=cmd("apply","Applications.");for(const n of ["staff","partner","creator"])sub(g,n,"Submit "+n+" application.",[S("answers","Application answers.")]);add(g);
add(cmd("applications","List applications.",P.ManageGuild).addStringOption(o=>o.setName("type").setDescription("Type.")));
for(const [n,d] of [["application-review","Review application."],["application-accept","Accept application."],["application-deny","Deny application."]])add(cmd(n,d,P.ManageGuild).addStringOption(S("id","Application ID.")));

add(cmd("remind","Create reminder.").addIntegerOption(I("minutes","Minutes.",1,525600)).addStringOption(S("message","Reminder.")),cmd("reminders","List reminders."),cmd("reminder-delete","Delete reminder.").addStringOption(S("id","Reminder ID.")),cmd("remindme","Create reminder.").addIntegerOption(I("minutes","Minutes.",1,525600)).addStringOption(S("message","Reminder.")));
add(cmd("afk","Set AFK.").addStringOption(S("reason","Reason.")),cmd("afk-remove","Remove AFK."),cmd("afk-list","List AFK users."));
add(cmd("starboard","Configure starboard.",P.ManageGuild).addChannelOption(C("channel")).addIntegerOption(I("stars","Stars.",1,50)),cmd("starboard-config","Configure starboard.",P.ManageGuild).addChannelOption(C("channel")).addIntegerOption(I("stars","Stars.",1,50)),cmd("starboard-disable","Disable starboard.",P.ManageGuild));
add(cmd("sticky","Set sticky.",P.ManageMessages).addStringOption(S("message","Message.")).addChannelOption(o=>o.setName("channel").setDescription("Channel.")),cmd("sticky-remove","Remove sticky.",P.ManageMessages).addChannelOption(o=>o.setName("channel").setDescription("Channel.")),cmd("sticky-list","List sticky messages."));
g=cmd("customcommand","Custom commands.",P.ManageGuild);sub(g,"add","Add.",[S("name","Name."),S("response","Response.")]);sub(g,"remove","Remove.",[S("name","Name.")]);sub(g,"list","List.");sub(g,"edit","Edit.",[S("name","Name."),S("response","Response.")]);add(g);
add(cmd("announce","Send announcement.",P.ManageMessages).addStringOption(S("message","Message.")).addChannelOption(o=>o.setName("channel").setDescription("Channel.")),cmd("announcement-edit","Edit announcement.",P.ManageMessages).addStringOption(S("message_id","Message ID.")).addStringOption(S("message","New message.")),cmd("announcement-delete","Delete announcement.",P.ManageMessages).addStringOption(S("message_id","Message ID.")));
add(cmd("addrole","Add role.",P.ManageRoles).addUserOption(U()).addRoleOption(o=>o.setName("role").setDescription("Role.").setRequired(true)),cmd("removerole","Remove role.",P.ManageRoles).addUserOption(U()).addRoleOption(o=>o.setName("role").setDescription("Role.").setRequired(true)));
g=cmd("role","Role management.",P.ManageRoles);sub(g,"create","Create role.",[S("name","Name.")]);sub(g,"delete","Delete role.",[S("role_id","Role ID.")]);sub(g,"add","Add role.",[U(),S("role_id","Role ID.")]);sub(g,"remove","Remove role.",[U(),S("role_id","Role ID.")]);sub(g,"info","Role info.",[S("role_id","Role ID.")]);sub(g,"list","List roles.");add(g);

add(cmd("staffinfo","Show staff roles."),cmd("staffannounce","Staff announcement.",P.ManageGuild).addStringOption(S("message","Message.")),cmd("staffnotes","Save staff note.",P.ManageGuild).addStringOption(S("note","Note.")),cmd("report","Report a member.").addUserOption(U()).addStringOption(S("reason","Reason.")),cmd("reports","List reports.",P.ManageGuild),cmd("modstats","Moderation stats.",P.ManageGuild),cmd("stafflist","List staff."));
add(cmd("say","Send message as bot.",P.ManageMessages).addStringOption(S("message","Message.")).addChannelOption(o=>o.setName("channel").setDescription("Channel.")));
add(cmd("embed","Send embed.",P.ManageMessages).addStringOption(S("title","Title.")).addStringOption(S("description","Description.")).addChannelOption(o=>o.setName("channel").setDescription("Channel.")));
add(cmd("poll","Create poll.",P.ManageMessages).addStringOption(S("question","Question.")).addStringOption(S("options","Options separated by |.")));
add(cmd("roleinfo","Show role info.").addRoleOption(o=>o.setName("role").setDescription("Role.").setRequired(true)));

add(cmd("autorole","Configure autorole.",P.ManageRoles).addRoleOption(o=>o.setName("role").setDescription("Role.").setRequired(true)),cmd("autorole-disable","Disable autorole.",P.ManageRoles));
add(cmd("reactionrole","Create reaction role.",P.ManageRoles).addRoleOption(o=>o.setName("role").setDescription("Role.").setRequired(true)).addStringOption(S("message","Panel message.")).addChannelOption(o=>o.setName("channel").setDescription("Channel.")));



const timer=(ctx,r)=>{const ms=Math.min(Math.max(1000,r.at-Date.now()),2147483647);setTimeout(async()=>{const u=await ctx.client.users.fetch(r.user).catch(()=>null);if(u)await u.send("Reminder: "+r.message).catch(()=>{});ctx.db.reminders=ctx.db.reminders.filter(x=>x.id!==r.id);ctx.save()},ms)};
const finish=(ctx,g)=>{const ms=Math.min(Math.max(1000,g.endsAt-Date.now()),2147483647);setTimeout(async()=>{if(g.ended)return;const a=[...g.entries],w=[];while(w.length<Math.min(g.winners,a.length)){const x=a[Math.floor(Math.random()*a.length)];if(!w.includes(x))w.push(x)}g.ended=true;g.winnerIds=w;ctx.save();const c=ctx.client.channels.cache.get(g.channel);if(c)await c.send("Giveaway ended: **"+g.prize+"** — "+(w.length?w.map(x=>"<@"+x+">").join(", "):"Nobody entered.")).catch(()=>{})},ms)};

async function handle(i,ctx){
 const db=ctx.db,n=i.commandName;
 if(["say","embed","announce-embed"].includes(n)){const c=ch(i,"channel")||i.channel;if(n==="say")await c.send({content:opt(i,"message"),allowedMentions:{parse:[]}});else await c.send({embeds:[new EmbedBuilder().setTitle(opt(i,"title")).setDescription(opt(i,"description")).setTimestamp()]});return out(i,"Sent.")}
 if(n==="poll"){const a=opt(i,"options").split("|").map(x=>x.trim()).filter(Boolean).slice(0,10);if(a.length<2)return out(i,"Use at least 2 options separated by |.");const m=await i.channel.send({embeds:[new EmbedBuilder().setTitle("Poll").setDescription("**"+opt(i,"question")+"**\\n\\n"+a.map((x,j)=>(j+1)+". "+x).join("\\n"))]});const nums=["1️⃣","2️⃣","3️⃣","4️⃣","5️⃣","6️⃣","7️⃣","8️⃣","9️⃣","🔟"];for(let j=0;j<a.length;j++)await m.react(nums[j]);return out(i,"Poll created.")}
 if(n==="stats"){const u=usr(i,"user")||i.user,d=db.levels?.[key(i.guild,u.id)]||{level:0,xp:0};return out(i,u.tag+" — Level "+d.level+" — "+d.xp+" XP")}
 if(n==="serverstats")return out(i,"Members: "+i.guild.memberCount+" | Channels: "+i.guild.channels.cache.size+" | Roles: "+i.guild.roles.cache.size);
 if(n==="roleinfo"){const r=i.options.getRole("role",true);return out(i,r.name+" — "+r.id+" — "+r.members.size+" members")}
 if(n==="channelinfo"){const c=ch(i,"channel")||i.channel;return out(i,c.name+" — "+c.id+" — type "+c.type)}
 if(n==="botinfo")return out(i,"The Hub Bot — discord.js — "+i.client.guilds.cache.size+" server(s)");
 if(n==="permissions")return out(i,i.memberPermissions.toArray().join(", ")||"No permissions");
 if(n==="setnick"){const m=i.guild.members.cache.get(usr(i,"user").id);if(!m)return out(i,"Member not found.");await m.setNickname(opt(i,"nickname")||null);return out(i,"Nickname updated.")}
 if(n==="autorole"){db.config.autorole=i.options.getRole("role",true).id;ctx.save();return out(i,"Autorole configured.")}
 if(n==="autorole-disable"){delete db.config.autorole;ctx.save();return out(i,"Autorole disabled.")}
 if(n==="reactionrole"){const c=ch(i,"channel")||i.channel,r=i.options.getRole("role",true),m=await c.send(opt(i,"message")+"\\nReact with 👍 to get "+r+".");await m.react("👍");db.reactionRoles??={};db.reactionRoles[m.id]={guild:i.guild.id,channel:c.id,role:r.id};ctx.save();return out(i,"Reaction-role panel created.")}
 if(n==="memberlist"){const r=i.options.getRole("role",true);return out(i,r.members.map(m=>m.user.tag).join("\\n").slice(0,1900)||"No members.")}
 if(n==="warn"||n==="warnings"||n==="clearwarnings"){const u=usr(i,"user"),k=key(i.guild,u.id);db.warnings??={};db.warnings[k]??=[];if(n==="warn"){db.warnings[k].push({by:i.user.id,reason:opt(i,"reason")||"No reason",at:Date.now()});ctx.save();return out(i,"Warned "+u.tag+".")}if(n==="warnings")return out(i,db.warnings[k].map((x,j)=>"#"+(j+1)+" "+x.reason).join("\\n")||"No warnings.");db.warnings[k]=[];ctx.save();return out(i,"Warnings cleared.")}
 if(n==="softban"){const m=i.guild.members.cache.get(usr(i,"user").id);if(!m)return out(i,"Member not found.");await m.ban({reason:opt(i,"reason")||"Softban"});await i.guild.members.unban(m.id);return out(i,"Softban complete.")}
 if(n==="lockdown"||n==="unlockdown"){await i.deferReply({ephemeral:true});for(const c of i.guild.channels.cache.values())if(c.isTextBased())await c.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:n==="lockdown"?false:null}).catch(()=>{});return i.editReply(n==="lockdown"?"Server lockdown enabled.":"Server lockdown disabled.")}
 if(n==="move"){const m=i.guild.members.cache.get(usr(i,"user").id),c=ch(i,"channel");if(!m?.voice.channel)return out(i,"Member is not in voice.");await m.voice.setChannel(c);return out(i,"Member moved.")}
 if(n==="ticket"||n==="ticket-panel"||n==="ticket-settings"){if(n==="ticket-panel"){await(ch(i,"channel")||i.channel).send("Support Tickets — use /ticket open.");return out(i,"Panel sent.")}if(n==="ticket-settings"){db.config.ticketCategory=ch(i,"category").id;ctx.save();return out(i,"Ticket category saved.")}const s=i.options.getSubcommand();if(s==="panel"){await ch(i,"channel").send("Support Tickets — use /ticket open.");return out(i,"Panel sent.")}if(s==="settings"){db.config.ticketCategory=ch(i,"category").id;ctx.save();return out(i,"Ticket category saved.")}const old=i.guild.channels.cache.find(c=>c.topic==="ticket:"+i.user.id);if(old)return out(i,"You already have "+old);const c=await i.guild.channels.create({name:"ticket-"+i.user.username.toLowerCase().replace(/[^a-z0-9]/g,"").slice(0,18),type:ChannelType.GuildText,parent:db.config.ticketCategory||null,topic:"ticket:"+i.user.id,permissionOverwrites:[{id:i.guild.roles.everyone.id,deny:[P.ViewChannel]},{id:i.user.id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory]},{id:i.client.user.id,allow:[P.ViewChannel,P.SendMessages,P.ManageChannels]}]});await c.send("Welcome "+i.user+"! Staff will help you. Use /close when finished.");return out(i,"Ticket created: "+c)}
 if(["close","add","remove","claim","unclaim","rename","transcript"].includes(n)){if(!i.channel?.topic?.startsWith("ticket:"))return out(i,"This is not a ticket.");if(n==="close"){await out(i,"Closing ticket...");setTimeout(()=>i.channel.delete().catch(()=>{}),1000);return}if(n==="add"||n==="remove"){const u=usr(i,"user");await i.channel.permissionOverwrites.edit(u.id,n==="add"?{ViewChannel:true,SendMessages:true}:{ViewChannel:false});return out(i,n==="add"?"Member added.":"Member removed.")}if(n==="claim"){db.tickets??={};db.tickets[i.channel.id]={claimedBy:i.user.id};ctx.save();return out(i,"Ticket claimed.")}if(n==="unclaim"){delete db.tickets?.[i.channel.id];ctx.save();return out(i,"Ticket unclaimed.")}if(n==="rename"){await i.channel.setName(opt(i,"name").toLowerCase().replace(/[^a-z0-9-]/g,"-").slice(0,100));return out(i,"Ticket renamed.")}const ms=await i.channel.messages.fetch({limit:100}),txt=[...ms.values()].reverse().map(m=>m.author.tag+": "+m.content).join("\\n");return i.reply({content:"Transcript",files:[{attachment:Buffer.from(txt||"Empty"),name:"transcript.txt"}],ephemeral:true})}
 if(n.startsWith("automod")){const s=n==="automod"?i.options.getSubcommand():n.replace("automod-","");if(s==="enable"){db.config.automod=true;ctx.save();return out(i,"Automod enabled.")}if(s==="disable"){db.config.automod=false;ctx.save();return out(i,"Automod disabled.")}if(s==="status")return out(i,"Automod: "+(db.config.automod?"enabled":"disabled"));db.config.badWords=opt(i,"words").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);ctx.save();return out(i,"Blocked words updated.")}
 if(["welcome","goodbye","welcome-config","welcome-test","goodbye-config","goodbye-test"].includes(n)){const type=n.startsWith("welcome")?"welcome":"goodbye";if(n==="welcome"||n==="goodbye"){const s=i.options.getSubcommand();if(s==="config"){db.config[type]=ch(i,"channel").id;ctx.save();return out(i,"Channel saved.")}const c=i.guild.channels.cache.get(db.config[type]);if(!c)return out(i,"Configure a channel first.");await c.send(type==="welcome"?"Welcome "+i.user+" to The Hub!":"Goodbye from The Hub!");return out(i,"Test sent.")}if(n.endsWith("-config")){db.config[type]=ch(i,"channel").id;ctx.save();return out(i,"Channel saved.")}const c=i.guild.channels.cache.get(db.config[type]);if(!c)return out(i,"Configure a channel first.");await c.send(type==="welcome"?"Welcome "+i.user+" to The Hub!":"Goodbye from The Hub!");return out(i,"Test sent.")}
 if(n==="birthday"){const s=i.options.getSubcommand(),k=key(i.guild,i.user.id);db.birthdays??={};if(s==="set"){const d=opt(i,"date");if(!/^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/.test(d))return out(i,"Use MM-DD.");db.birthdays[k]=d;ctx.save();return out(i,"Birthday saved.")}if(s==="remove"){delete db.birthdays[k];ctx.save();return out(i,"Birthday removed.")}if(s==="view"){const u=usr(i,"user")||i.user;return out(i,db.birthdays[key(i.guild,u.id)]||"No birthday saved.")}if(s==="config"){db.config.birthdayChannel=ch(i,"channel").id;ctx.save();return out(i,"Birthday channel saved.")}if(s==="test"){const c=i.guild.channels.cache.get(db.config.birthdayChannel);if(c)await c.send("Birthday test.");return out(i,"Test sent.")}let a=Object.entries(db.birthdays).filter(([x])=>x.startsWith(i.guild.id+":"));if(s==="today"){const t=new Date().toISOString().slice(5,10);a=a.filter(x=>x[1]===t)}return out(i,a.map(x=>"<@"+x[0].split(":")[1]+"> — "+x[1]).join("\\n")||"None found.")}
 if(n==="level"||n==="levels"||n==="level-config"||n==="level-rewards"){db.levels??={};if(n==="levels")return out(i,"Leveling is "+(db.config.leveling===false?"disabled":"enabled")+".");if(n==="level-config"){db.config.leveling=opt(i,"enabled").toLowerCase()==="true";ctx.save();return out(i,"Leveling "+(db.config.leveling?"enabled":"disabled")+".")}if(n==="level-rewards"){const r=i.guild.roles.cache.get(opt(i,"role_id"));if(!r)return out(i,"Role not found.");db.config.levelRewards??={};db.config.levelRewards[i.options.getInteger("level",true)]=r.id;ctx.save();return out(i,"Reward saved.")}const s=i.options.getSubcommand();if(s==="config"){db.config.leveling=opt(i,"enabled").toLowerCase()==="true";ctx.save();return out(i,"Leveling "+(db.config.leveling?"enabled":"disabled")+".")}if(s==="rewards"){const r=i.guild.roles.cache.get(opt(i,"role_id"));if(!r)return out(i,"Role not found.");db.config.levelRewards??={};db.config.levelRewards[i.options.getInteger("level",true)]=r.id;ctx.save();return out(i,"Reward saved.")}if(s==="leaderboard"){const a=Object.entries(db.levels).filter(([x])=>x.startsWith(i.guild.id+":")).sort((a,b)=>b[1].level-a[1].level||b[1].xp-a[1].xp).slice(0,10);return out(i,a.map((x,j)=>(j+1)+". <@"+x[0].split(":")[1]+"> — L"+x[1].level+" ("+x[1].xp+" XP)").join("\\n")||"No levels.")}const u=usr(i,s==="view"||s==="rank"?"user")||i.user,d=db.levels[key(i.guild,u.id)]||{level:0,xp:0};return out(i,u.tag+" — Level "+d.level+" — "+d.xp+" XP")}
 if(n==="giveaway"){const s=i.options.getSubcommand();db.giveaways??={};if(s==="enter"){const g=db.giveaways[opt(i,"id")];if(!g||g.ended)return out(i,"Giveaway inactive.");if(!g.entries.includes(i.user.id))g.entries.push(i.user.id);ctx.save();return out(i,"Entered.")}if(s==="list")return out(i,Object.values(db.giveaways).filter(x=>x.guild===i.guild.id).map(x=>x.id+" — "+x.prize+" — "+(x.ended?"ended":"active")).join("\\n")||"No giveaways.");if(s==="start"){const x={id:Date.now().toString(36),guild:i.guild.id,channel:i.channel.id,prize:opt(i,"prize"),winners:i.options.getInteger("winners")||1,endsAt:Date.now()+i.options.getInteger("minutes",true)*60000,entries:[],ended:false};db.giveaways[x.id]=x;ctx.save();await i.channel.send("Giveaway: **"+x.prize+"** — ID: "+x.id);finish(ctx,x);return out(i,"Giveaway started.")}const x=db.giveaways[opt(i,"id")];if(!x)return out(i,"Giveaway not found.");if(s==="cancel"){x.ended=true;ctx.save();return out(i,"Cancelled.")}if(s==="reroll"){if(!x.entries.length)return out(i,"Nobody entered.");return out(i,"Rerolled winner: <@"+x.entries[Math.floor(Math.random()*x.entries.length))+">")}x.endsAt=Date.now();x.ended=false;ctx.save();finish(ctx,x);return out(i,"Ending giveaway.")}
 if(n==="suggest"||n==="suggestions"||n.startsWith("suggestion-")){db.suggestions??={};if(n==="suggest"){const id=Date.now().toString(36);db.suggestions[id]={id,guild:i.guild.id,user:i.user.id,text:opt(i,"text"),status:"pending"};ctx.save();return out(i,"Suggestion submitted: "+id)}if(n==="suggestions")return out(i,Object.values(db.suggestions).filter(x=>x.guild===i.guild.id).slice(-15).map(x=>x.id+" — "+x.status+" — "+x.text).join("\\n")||"No suggestions.");const x=db.suggestions[opt(i,"id")];if(!x)return out(i,"Suggestion not found.");if(n==="suggestion-approve")x.status="approved";if(n==="suggestion-deny")x.status="denied";ctx.save();return out(i,"Suggestion is "+x.status+".")}
 if(n==="apply"){const type=i.options.getSubcommand(),id=Date.now().toString(36);db.applications??={};db.applications[id]={id,guild:i.guild.id,user:i.user.id,type,answers:opt(i,"answers"),status:"pending"};ctx.save();return out(i,"Application submitted: "+id)}
 if(n==="applications"){const t=opt(i,"type"),a=Object.values(db.applications||{}).filter(x=>x.guild===i.guild.id&&(!t||x.type===t));return out(i,a.slice(-20).map(x=>x.id+" — "+x.type+" — "+x.status).join("\\n")||"No applications.")}
 if(n.startsWith("application-")){const x=db.applications?.[opt(i,"id")];if(!x)return out(i,"Application not found.");if(n==="application-accept")x.status="accepted";if(n==="application-deny")x.status="denied";ctx.save();return out(i,"Application is "+x.status+".")}
 if(n==="remind"||n==="remindme"){const r={id:Date.now().toString(36),guild:i.guild.id,user:i.user.id,message:opt(i,"message"),at:Date.now()+i.options.getInteger("minutes",true)*60000};db.reminders??=[];db.reminders.push(r);ctx.save();timer(ctx,r);return out(i,"Reminder set: "+r.id)}
 if(n==="reminders")return out(i,(db.reminders||[]).filter(x=>x.user===i.user.id).map(x=>x.id+" — "+x.message).join("\\n")||"No reminders.");
 if(n==="reminder-delete"){const id=opt(i,"id"),before=(db.reminders||[]).length;db.reminders=db.reminders.filter(x=>!(x.id===id&&x.user===i.user.id));ctx.save();return out(i,before===db.reminders.length?"Not found.":"Deleted.")}
 if(n==="afk"){db.afk??={};db.afk[key(i.guild,i.user.id)]=opt(i,"reason")||"AFK";ctx.save();return out(i,"AFK set.")}if(n==="afk-remove"){delete db.afk?.[key(i.guild,i.user.id)];ctx.save();return out(i,"AFK removed.")}if(n==="afk-list"){const a=Object.entries(db.afk||{}).filter(([x])=>x.startsWith(i.guild.id+":"));return out(i,a.map(x=>"<@"+x[0].split(":")[1]+"> — "+x[1]).join("\\n")||"No AFK users.")}
 if(n==="starboard"||n==="starboard-config"){db.config.starboard={channel:ch(i,"channel").id,stars:i.options.getInteger("stars",true)};ctx.save();return out(i,"Starboard configured.")}if(n==="starboard-disable"){db.config.starboard=null;ctx.save();return out(i,"Starboard disabled.")}
 if(n==="sticky"){db.sticky??={};const c=ch(i,"channel")||i.channel;db.sticky[c.id]={message:opt(i,"message")};ctx.save();return out(i,"Sticky configured.")}if(n==="sticky-remove"){const c=ch(i,"channel")||i.channel;delete db.sticky?.[c.id];ctx.save();return out(i,"Sticky removed.")}if(n==="sticky-list")return out(i,Object.entries(db.sticky||{}).map(x=>"<#"+x[0]+"> — "+x[1].message).join("\\n")||"No sticky messages.");
 if(n==="customcommand"){const s=i.options.getSubcommand();db.customCommands??={};db.customCommands[i.guild.id]??={};const c=db.customCommands[i.guild.id];if(s==="list")return out(i,Object.keys(c).join(", ")||"None.");const name=opt(i,"name").toLowerCase();if(s==="remove")delete c[name];else c[name]=opt(i,"response");ctx.save();return out(i,"Custom command saved.")}
 if(n==="announce"){const c=ch(i,"channel")||i.channel;await c.send({embeds:[new EmbedBuilder().setTitle("Announcement").setDescription(opt(i,"message")).setTimestamp()]});return out(i,"Announcement sent.")}
 if(n==="announcement-edit"){const m=await (ch(i,"channel")||i.channel).messages.fetch(opt(i,"message_id"));await m.edit(opt(i,"message"));return out(i,"Edited.")}
 if(n==="announcement-delete"){const m=await (ch(i,"channel")||i.channel).messages.fetch(opt(i,"message_id"));await m.delete();return out(i,"Deleted.")}
 if(n==="addrole"||n==="removerole"){const m=i.guild.members.cache.get(usr(i,"user").id),r=i.options.getRole("role");if(!m)return out(i,"Member not found.");n==="addrole"?await m.roles.add(r):await m.roles.remove(r);return out(i,"Role updated.")}
 if(n==="role"){const s=i.options.getSubcommand();if(s==="list")return out(i,i.guild.roles.cache.map(r=>r.name).join(", "));if(s==="create"){const r=await i.guild.roles.create({name:opt(i,"name")});return out(i,"Created "+r+".")}const r=i.guild.roles.cache.get(opt(i,"role_id"));if(!r)return out(i,"Role not found.");if(s==="delete"){await r.delete();return out(i,"Deleted.")}if(s==="info")return out(i,r.name+" — "+r.id+" — "+r.members.size+" members");const m=i.guild.members.cache.get(usr(i,"user").id);if(!m)return out(i,"Member not found.");s==="add"?await m.roles.add(r):await m.roles.remove(r);return out(i,"Role updated.")}
 if(n==="staffinfo")return out(i,"Staff roles: "+staff.join(", "));
 if(n==="staffannounce"){const c=i.guild.channels.cache.find(x=>x.name==="staff-announcements"&&x.isTextBased());if(!c)return out(i,"Create #staff-announcements first.");await c.send(opt(i,"message"));return out(i,"Sent.")}
 if(n==="staffnotes"){db.staffNotes??=[];db.staffNotes.push({guild:i.guild.id,user:i.user.id,note:opt(i,"note"),at:Date.now()});ctx.save();return out(i,"Note saved.")}
 if(n==="report"){db.reports??=[];db.reports.push({guild:i.guild.id,user:usr(i,"user").id,reason:opt(i,"reason"),by:i.user.id,at:Date.now()});ctx.save();return out(i,"Report submitted.")}
 if(n==="reports")return out(i,(db.reports||[]).filter(x=>x.guild===i.guild.id).slice(-20).map(x=>"<@"+x.user+"> — "+x.reason).join("\\n")||"No reports.");
 if(n==="modstats")return out(i,"Warnings: "+Object.values(db.warnings||{}).reduce((a,x)=>a+x.length,0)+" | Reports: "+(db.reports||[]).length);
 if(n==="stafflist")return out(i,i.guild.members.cache.filter(m=>m.roles.cache.some(r=>staff.includes(r.name))).map(m=>m.user.tag).join("\\n")||"No staff found.");
 return false;
}
function init(ctx){for(const r of ctx.db.reminders||[])if(r.at>Date.now())timer(ctx,r);for(const g of Object.values(ctx.db.giveaways||{}))if(!g.ended&&g.endsAt>Date.now())finish(ctx,g)}
module.exports={commands,handle,init};